USE lolmatchups;
INSERT INTO champion VALUES 
(122,"Darius","the Hand of Noxus"),
(12,"Alistar","the Minotaur"),
(17,"Teemo","the Swift Scout"),
(77,"Udyr","the Spirit Walker"),
(84,"Akali","the Fist of Shadow"),
(222,"Jinx","the Loose Cannon"),
(16,"Soraka","the Starchild"),
(1,"Annie","the Dark Child"),
(121,"Khazix","the Voidreaver"),
(4,"TwistedFate","the Card Master"),
(90,"Malzahar","the Prophet of the Void"),
(10,"Kayle","The Judicator"),
(75,"Nasus","the Curator of the Sands"),
(51,"Caitlyn","the Sheriff of Piltover"),
(54,"Malphite","Shard of the Monolith"),
(79,"Gragas","the Rabble Rouser"),
(22,"Ashe","the Frost Archer"),
(106,"Volibear","the Thunder's Roar"),
(56,"Nocturne","the Eternal Nightmare"),
(131,"Diana","Scorn of the Moon"),
(35,"Shaco","the Demon Jester"),
(83,"Yorick","the Gravedigger"),
(43,"Karma","the Enlightened One"),
(92,"Riven","the Exile"),
(412,"Thresh","the Chain Warden"),
(30,"Karthus","the Deathsinger"),
(61,"Orianna","the Lady of Clockwork"),
(33,"Rammus","the Armordillo"),
(112,"Viktor","the Machine Herald"),
(78,"Poppy","the Iron Ambassador"),
(99,"Lux","the Lady of Luminosity"),
(429,"Kalista","the Spear of Vengeance"),
(101,"Xerath","the Magus Ascendant"),
(2,"Olaf","the Berserker"),
(26,"Zilean","the Chronokeeper"),
(113,"Sejuani","the Winter's Wrath"),
(110,"Varus","the Arrow of Retribution"),
(421,"RekSai","the Void Burrower"),
(134,"Syndra","the Dark Sovereign"),
(98,"Shen","Eye of Twilight"),
(50,"Swain","the Master Tactician"),
(36,"DrMundo","the Madman of Zaun"),
(3,"Galio","the Sentinel's Sorrow"),
(60,"Elise","The Spider Queen"),
(89,"Leona","the Radiant Dawn"),
(120,"Hecarim","the Shadow of War"),
(62,"MonkeyKing","the Monkey King"),
(8,"Vladimir","the Crimson Reaper"),
(254,"Vi","the Piltover Enforcer"),
(37,"Sona","Maven of the Strings"),
(150,"Gnar","the Missing Link"),
(45,"Veigar","the Tiny Master of Evil"),
(105,"Fizz","the Tidal Trickster"),
(24,"Jax","Grandmaster at Arms"),
(80,"Pantheon","the Artisan of War"),
(57,"Maokai","the Twisted Treant"),
(91,"Talon","the Blade's Shadow"),
(48,"Trundle","the Troll King"),
(14,"Sion","The Undead Juggernaut"),
(103,"Ahri","the Nine-Tailed Fox"),
(96,"KogMaw","the Mouth of the Abyss"),
(38,"Kassadin","the Void Walker"),
(31,"Chogath","the Terror of the Void"),
(127,"Lissandra","the Ice Witch"),
(104,"Graves","the Outlaw"),
(102,"Shyvana","the Half-Dragon"),
(18,"Tristana","the Yordle Gunner"),
(29,"Twitch","the Plague Rat"),
(13,"Ryze","the Rogue Mage"),
(82,"Mordekaiser","the Master of Metal"),
(39,"Irelia","the Will of the Blades"),
(34,"Anivia","the Cryophoenix"),
(154,"Zac","the Secret Weapon"),
(28,"Evelynn","the Widowmaker"),
(267,"Nami","the Tidecaller"),
(114,"Fiora","the Grand Duelist"),
(59,"JarvanIV","the Exemplar of Demacia"),
(238,"Zed","the Master of Shadows"),
(68,"Rumble","the Mechanized Menace"),
(63,"Brand","the Burning Vengeance"),
(126,"Jayce","the Defender of Tomorrow"),
(40,"Janna","the Storm's Fury"),
(161,"Velkoz","the Eye of the Void"),
(67,"Vayne","the Night Hunter"),
(85,"Kennen","the Heart of the Tempest"),
(72,"Skarner","the Crystal Vanguard"),
(76,"Nidalee","the Bestial Huntress"),
(117,"Lulu","the Fae Sorceress"),
(58,"Renekton","the Butcher of the Sands"),
(107,"Rengar","the Pridestalker"),
(20,"Nunu","the Yeti Rider"),
(157,"Yasuo","the Unforgiven"),
(64,"LeeSin","the Blind Monk"),
(201,"Braum","the Heart of the Freljord"),
(42,"Corki","the Daring Bombardier"),
(32,"Amumu","the Sad Mummy"),
(53,"Blitzcrank","the Great Steam Golem"),
(15,"Sivir","the Battle Mistress"),
(268,"Azir","the Emperor of the Sands"),
(7,"Leblanc","the Deceiver"),
(119,"Draven","the Glorious Executioner"),
(432,"Bard","the Wandering Caretaker"),
(133,"Quinn","Demacia's Wings"),
(55,"Katarina","the Sinister Blade"),
(44,"Taric","the Gem Knight"),
(266,"Aatrox","the Darkin Blade"),
(86,"Garen","The Might of Demacia"),
(41,"Gangplank","the Saltwater Scourge"),
(9,"FiddleSticks","the Harbinger of Doom"),
(111,"Nautilus","the Titan of the Depths"),
(115,"Ziggs","the Hexplosives Expert"),
(19,"Warwick","the Blood Hunter"),
(236,"Lucian","the Purifier"),
(21,"MissFortune","the Bounty Hunter"),
(74,"Heimerdinger","the Revered Inventor"),
(27,"Singed","the Mad Chemist"),
(81,"Ezreal","the Prodigal Explorer"),
(6,"Urgot","the Headsman's Pride"),
(143,"Zyra","Rise of the Thorns"),
(11,"MasterYi","the Wuju Bladesman"),
(25,"Morgana","Fallen Angel"),
(23,"Tryndamere","the Barbarian King"),
(5,"XinZhao","the Seneschal of Demacia"),
(69,"Cassiopeia","the Serpent's Embrace");