USE lolmatchups;
INSERT INTO mastery VALUES 
(4222,"Veteran's Scars","\+12 Health","\+24 Health","\+36 Health",NULL,"Defense",5),
(4151,"Frenzy","Critical hits grant \+5% Attack Speed for 3 seconds \(stacks up to 3 times\)",NULL,NULL,NULL,"Offense",16),
(4152,"Devastating Strikes","\+2% Armor and Magic Penetration","\+4% Armor and Magic Penetration","\+6% Armor and Magic Penetration",NULL,"Offense",17),
(4221,"Unyielding","Melee \- Reduces all incoming damage from champions by 2\<br\>Ranged \- Reduces all incoming damage from champions by 1",NULL,NULL,NULL,"Defense",4),
(4154,"Arcane Blade","Basic Attacks also deal bonus magic damage equal to 5% of Ability Power",NULL,NULL,NULL,"Offense",18),
(4322,"Summoner's Insight","Reduces the cooldown of Summoner Spells by 4%","Reduces the cooldown of Summoner Spells by 7%","Reduces the cooldown of Summoner Spells by 10%",NULL,"Utility",4),
(4224,"Bladed Armor","Taking Basic Attack Damage from neutral monsters cause them to bleed, dealing physical damage equal to 1% of their current Health each second\<br\>This does not work against lane minions",NULL,NULL,NULL,"Defense",6),
(4124,"Feast","Killing a unit restores 3 Health and 1 Mana",NULL,NULL,NULL,"Offense",7),
(4114,"Butcher","Basic attacks and single target spells deal an additional 2 damage to minions and monsters\<br\>\<br\>This does not trigger off of area of effect damage or damage over time effects",NULL,NULL,NULL,"Offense",3),
(4133,"Arcane Mastery","\+6 Ability Power",NULL,NULL,NULL,"Offense",10),
(4131,"Spell Weaving","Damaging an enemy champion with a Basic Attack increases Spell Damage by 1%, stacking up to 3 times \(max 3% damage increase\)",NULL,NULL,NULL,"Offense",8),
(4111,"Double-Edged Sword","Melee \- Deal an additional 2% damage and receive an additional 1% damage\<br\>Ranged \- Deal an additional 1.5% damage and receive an additional 1.5% damage",NULL,NULL,NULL,"Offense",0),
(4112,"Fury","\+1.25% Attack Speed","\+2.5% Attack Speed","\+3.75% Attack Speed","\+5% Attack Speed","Offense",1),
(4113,"Sorcery","\+1.25% Cooldown Reduction","\+2.5% Cooldown Reduction","\+3.75% Cooldown Reduction","\+5% Cooldown Reduction","Offense",2),
(4144,"Dangerous Game","Champion kills and assists restore 5% missing Health and Mana",NULL,NULL,NULL,"Offense",15),
(4214,"Tough Skin","Reduces damage taken from neutral monsters by 1\<br\>\<br\>This does not affect lane minions","Reduces damage taken from neutral monsters by 2\<br\>\<br\>This does not affect lane minions",NULL,NULL,"Defense",3),
(4213,"Enchanted Armor","Increases bonus Armor and Magic Resist by 2.5%","Increases bonus Armor and Magic Resist by 5%",NULL,NULL,"Defense",2),
(4331,"Greed","\+0.5 Gold every 10 seconds","\+1 Gold every 10 seconds","\+1.5 Gold every 10 seconds",NULL,"Utility",7),
(4334,"Culinary Master","Health potions are upgraded into Biscuits that restore an additional 20 Health and 10 Mana instantly upon consumption",NULL,NULL,NULL,"Utility",10),
(4123,"Mental Force","\+6 Ability Power at level 18 \(\+0.33 Ability Power per level\)","\+11 Ability Power at level 18 \(\+0.61 Ability Power per level\)","\+16 Ability Power at level 18 \(\+0.89 Ability Power per level\)",NULL,"Offense",6),
(4323,"Strength of Spirit","\+1 Health Regen per 5 seconds for every 300 maximum Mana",NULL,NULL,NULL,"Utility",5),
(4333,"Vampirism","\+1% Lifesteal and Spellvamp","\+2% Lifesteal and Spellvamp","\+3% Lifesteal and Spellvamp",NULL,"Utility",9),
(4341,"Scavenger","\+1 Gold each time an ally kills a nearby lane minion",NULL,NULL,NULL,"Utility",11),
(4132,"Martial Mastery","\+4 Attack Damage",NULL,NULL,NULL,"Offense",9),
(4343,"Expanded Mind","\+2% increased maximum Mana","\+3.5% increased maximum Mana","\+5% increased maximum Mana",NULL,"Utility",13),
(4342,"Wealth","\+40 Starting Gold",NULL,NULL,NULL,"Utility",12),
(4262,"Tenacious","Reduces the duration of crowd control effects by 15%",NULL,NULL,NULL,"Defense",18),
(4344,"Inspiration","\+5 Experience every 10 seconds while near a higher level allied champion","\+10 Experience every 10 seconds while near a higher level allied champion",NULL,NULL,"Utility",14),
(4362,"Wanderer","\+5% Movement Speed out of combat",NULL,NULL,NULL,"Utility",17),
(4242,"Swiftness","Reduces the effectiveness of slows by 10%",NULL,NULL,NULL,"Defense",12),
(4243,"Reinforced Armor","Reduces the total damage taken from critical strikes by 10%",NULL,NULL,NULL,"Defense",13),
(4244,"Evasive","Reduces damage taken by 4% from Area of Effect magic damage",NULL,NULL,NULL,"Defense",14),
(4324,"Alchemist","Increases the duration of potions and elixirs by 10%",NULL,NULL,NULL,"Utility",6),
(4312,"Fleet of Foot","\+0.5% Movement Speed","\+1% Movement Speed","\+1.5% Movement Speed",NULL,"Utility",1),
(4313,"Meditation","\+1 Mana Regen per 5 seconds","\+2 Mana Regen per 5 seconds","\+3 Mana Regen per 5 seconds",NULL,"Utility",2),
(4141,"Blade Weaving","Damaging an enemy champion with a spell increases Basic Attack Damage by 1%, stacking up to 3 times \(max 3% damage increase\)",NULL,NULL,NULL,"Offense",12),
(4311,"Phasewalker","Reduces the casting time of Recall by 1 second\<br\>\<br\>Dominion \- Reduces the casting time of Enhanced Recall by 0.5 seconds",NULL,NULL,NULL,"Utility",0),
(4121,"Expose Weakness","Damaging an enemy with a spell increases allied champions' damage to that enemy by 1% for the next 3 seconds",NULL,NULL,NULL,"Offense",4),
(4212,"Recovery","\+1 Health per 5 seconds","\+2 Health per 5 seconds",NULL,NULL,"Defense",1),
(4211,"Block","Reduces incoming damage from champion basic attacks by 1","Reduces incoming damage from champion basic attacks by 2",NULL,NULL,"Defense",0),
(4122,"Brute Force","\+4 Attack Damage at level 18 \(\+0.22 Attack Damage per level\)","\+7 Attack Damage at level 18 \(\+0.39 Attack Damage per level\)","\+10 Attack Damage at level 18 \(\+0.55 Attack Damage per level\)",NULL,"Offense",5),
(4143,"Archmage","Increases Ability Power by 2%","Increases Ability Power by 3.5%","Increases Ability Power by 5%",NULL,"Offense",14),
(4253,"Runic Blessing","Start the game with a 50 Health shield. This shield regenerates each time after respawning",NULL,NULL,NULL,"Defense",17),
(4332,"Runic Affinity","Increases the duration of shrine, relic, quest, and neutral monster buffs by 20%",NULL,NULL,NULL,"Utility",8),
(4134,"Executioner","Increases damage dealt to champions below 20% Health by 5%","Increases damage dealt to champions below 35% Health by 5%","Increases damage dealt to champions below 50% Health by 5%",NULL,"Offense",11),
(4252,"Legendary Guardian","\+1 Armor and 0.5 Magic Resist for each nearby enemy champion","\+2 Armor and 1 Magic Resist for each nearby enemy champion","\+3 Armor and 1.5 Magic Resist for each nearby enemy champion","\+4 Armor and 2 Magic Resist for each nearby enemy champion","Defense",16),
(4241,"Perseverance ","Regenerates 0.35% of missing Health every 5 seconds","Regenerates 0.675% of missing Health every 5 seconds","Regenerates 1% of missing Health every 5 seconds",NULL,"Defense",11),
(4142,"Warlord","Increases bonus Attack Damage by 2%","Increases Bonus Attack Damage by 3.5%","Increases Bonus Attack Damage by 5%",NULL,"Offense",13),
(4352,"Bandit","Melee \- Grants \+15 Gold on champion kill or assist\<br\>Ranged \- Grants \+3 Gold each time an enemy champion is attacked. This cannot trigger on the same champion more than once every 5 seconds",NULL,NULL,NULL,"Utility",15),
(4353,"Intelligence","\+2% Cooldown Reduction and reduces the cooldown of Activated Items by 4%","\+3.5% Cooldown Reduction and reduces the cooldown of Activated Items by 7%","\+5% Cooldown Reduction and reduces the cooldown of Activated Items by 10%",NULL,"Utility",16),
(4314,"Scout","Increases the cast range of trinket items by 15%",NULL,NULL,NULL,"Utility",3),
(4234,"Resistance","\+2 Magic Resist","\+3.5 Magic Resist","\+5 Magic Resist",NULL,"Defense",10),
(4251,"Second Wind","Increases self\-healing, Health Regen, Lifesteal, and Spellvamp by 10% when below 25% Health",NULL,NULL,NULL,"Defense",15),
(4162,"Havoc","\+3% increased damage",NULL,NULL,NULL,"Offense",19),
(4231,"Oppression","Reduces damage taken by 3% from enemies that have impaired movement \(slows, snares, taunts, stuns, etc.\)",NULL,NULL,NULL,"Defense",7),
(4233,"Hardiness","\+2 Armor","\+3.5 Armor","\+5 Armor",NULL,"Defense",9),
(4232,"Juggernaut","\+3% Maximum Health",NULL,NULL,NULL,"Defense",8);